# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/ (optional)
url: "https://philippemiron.github.io/" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Philippe Miron Ph. D. # Your name will go here
  description: "Personal website" # used by search engines

  # Header and footer text
  header_text: >
     <h1>Assistant Scientist</h1>
     <p>Turning data into science at the University of Miami<p>
  header_text_feature_image:
  footer_text: >
   Made with <i class="far fa-fw fa-heart"> and powered by <a href="http://jekyllrb.com">Jekyll</a></i>

  # Icons
  rss: false
  email_address: philippemiron@gmail.com
  twitter: philippemiron
  github: philippemiron
  uwebsite: https://nonlinear.rsmas.miami.edu/ #university group website
  instagram: philippemiron
  linkedin: philippemiron
  gscholar: https://scholar.google.com/citations?user=XEtG4h0AAAAJ&hl=en # full address
  #facebook:
  #reddit:
  #stack_exchange:  # Full URL
  #youtube:

  # Scripts
  google_analytics: "UA-167579461-1" # Tracking ID, e.g. "UA-000000-01"

  # Localization strings
  str_follow_on: "Follow on"
  str_email: "Connect via Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Read more &raquo;"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Lato:300,400,700,300italic,700italic|Abril+Fatface"

# PAGINATION
paginate: 100
paginate_path: "blog/page:num"

# COLLECTIONS
collections:
  projects:
    output: true
    permalink: /projects/:path/

# BUILD SETTINGS
markdown: kramdown

sass:
  sass_dir: _sass
  style: :compressed

plugins:
  - jekyll-paginate
